# .github/actions/setup-env/action.yml
name: 'Setup Node Environment'
description: 'Sets up Node and installs dependencies'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 24
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      shell: bash