name: React CI/CD

on:
  push:
    branches:
      - main
      - dev
      - qa
      - uat


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-env 

      - name: Run tests
        run: npm run test -- --run

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-env 

      # CHANGED STEP: Dynamically pass the current branch name to Vite/React build
      - name: Build project for specific environment
        run: |
          echo "Building the project specifically for the ${{ github.ref_name }} branch"
          npm run build -- --mode ${{ github.ref_name }}

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to allow the App to push to your gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-env 

      # NEW: This step generates your VIP Token on the fly!
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          app-id: ${{ vars.ACTION_APP_ID }}
          private-key: ${{ secrets.ACTION_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Deploy to GitHub Pages
        env:
          # Use the VIP token generated in the step above
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name "sreeraj-cicd-bot[bot]"
          git config --global user.email "sreeraj-cicd-bot[bot]@users.noreply.github.com"
          
          # This uses your VIP token to authenticate the push
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          npm run deploy